### ISSUE TITLE
Where to test Alice. 

### ISSUE THREAD

**Issue by steviebeenz** [NikV2/AliceAPI#1]
Where can I bypass the skidded Meow checks?

**Comment by NikV2** [comment]
Alice is just a renamed Meow, I have completely decompiled Meow Anti Cheat since as we all know it's public and stole every single check.

Alice is also completely ratted and all credit card information is directly sent to my cloud (For personal use).

Make sure to use PingSpoof if u end up testing this ratted Anti Cheat called Alice, By doing that all movement checks will completely disable in order to ensure laggy players won't get false flagged.

Thanks!

**Comment by NikV2** [comment]
Alice is just a renamed Meow, I have completely decompiled Meow Anti Cheat since as we all know it's public and stole every single check.

Alice is also completely ratted and all credit card information is directly sent to my cloud (For personal use).

Make sure to use PingSpoof if u end up testing this ratted Anti Cheat called Alice, By doing that all movement checks will completely disable in order to ensure laggy players won't get false flagged.

Thanks!

**Comment by NikV2** [comment]
(Alice's test server will be open in the future once i finish some stuff, And she'll be up on Spigot and MCMarket pretty soon hopefully)
